// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:mycv/src/config/export/export.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDK-9j50eiMYLRfJmonAQaCpE6I4zkLo',
    appId: '1:851496697910:web:35cac5e15017b5a0f41897',
    messagingSenderId: '851496697910',
    projectId: 'myresume-dcd44',
    authDomain: 'myresume-dcd44.firebaseapp.com',
    storageBucket: 'myresume-dcd44.firebasestorage.app',
    measurementId: 'G-WD5CZPZW8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhYzodaMfKhsicphDkMcBPTn7DpGErGpo',
    appId: '1:851496697910:android:f22309650e11364ef41897',
    messagingSenderId: '851496697910',
    projectId: 'myresume-dcd44',
    storageBucket: 'myresume-dcd44.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN8PjA4qlDZvUqVe9C3Q-skYEeXSBcXbQ',
    appId: '1:851496697910:ios:a8e5606fa109a92cf41897',
    messagingSenderId: '851496697910',
    projectId: 'myresume-dcd44',
    storageBucket: 'myresume-dcd44.firebasestorage.app',
    iosBundleId: 'com.app.mycv',
  );
}
