// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCXdhx3mcFLsQtcOlEhCvFkIH-unE0QwA',
    appId: '1:957734125189:web:0a41e1b41825623f54f3ec',
    messagingSenderId: '957734125189',
    projectId: 'myresume-b669c',
    authDomain: 'myresume-b669c.firebaseapp.com',
    storageBucket: 'myresume-b669c.firebasestorage.app',
    measurementId: 'G-VKFKB2LXWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqNSqDTx_g7Lb6sYJq-9569xSGnGivps',
    appId: '1:957734125189:android:e3a9e8f72b492b9354f3ec',
    messagingSenderId: '957734125189',
    projectId: 'myresume-b669c',
    storageBucket: 'myresume-b669c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTK8X8p68psXHVZAGKcqKbd4mCgjFWXa4',
    appId: '1:957734125189:ios:3c941d64c805d17354f3ec',
    messagingSenderId: '957734125189',
    projectId: 'myresume-b669c',
    storageBucket: 'myresume-b669c.firebasestorage.app',
    iosBundleId: 'com.app.mycv',
  );
}
